# Site settings
title: "Блог о выпечке, пошаговые рецепты с фото - cookroom.com.ua"
email: info@cookroom.com.ua
description: >
  Блог о вкусной и доступной выпечке.
  Пироги, кексы, печенье, торты, десерты и  другие сладкие радости
  вы можете найти на кулинарном блоге о выпечке.
  Многие из рецептов с пошаговыми фото и подробными описаниями.
  Здесь можно увидеть не только поверенные рецепты выпечки, но и новые эксперименты.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cookroom.com.ua" # the base hostname & protocol for your site
timezone: Europe/Kiev
paginate: 5
permalink: /:year/:month/:day/:title.html

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
tags_dir: tag
exclude: ["*.sublime-*", "tmpdata/"]
